### ISSUE TITLE
Doesn't work when tracking variables added to URL

### ISSUE THREAD

**Issue by ianb** [jsha/learnrust#6]
In Facebook Messenger the link was rewritten to:

https://wordlyze.crud.net/?fbclid=IwAR3z0NVvLQNtRa02yDaAsyzw07Q-BM9nwALUE8Qutiv0jMFky-GCjfxTeJM

This caused the app not to work, creating URLs like https://wordlyze.crud.net/?fbclid=IwAR3z0NVvLQNtRa02yDaAsyzw07Q-BM9nwALUE8Qutiv0jMFky-GCjfxTeJManalyze/test

If you use `location.pathname` here that'll probably fix it: https://github.com/jsha/learnrust/blob/master/wordle/index.html#L60

**Comment by jsha** [comment]
Thanks for the report! Fixed.
